[workspace]
members = [
    "crates/refal-ast",
    "crates/refal-syntax",
    "crates/refal-semantics",
    "crates/refal-runtime",
    "crates/refal-core",
    "crates/refal-cli",
    "crates/xtask"
]
resolver = "2"

[workspace.package]
version = "0.10.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Abhinav-Rust/REFAL-SUPERSYSTEM"
authors = ["Abhinav"]

[workspace.lints.rust]
unsafe_code = "forbid"
